### ISSUE TITLE
Can't build copilot-core 2.1.2 on GHC 7.10.2

### ISSUE THREAD

**Issue by octopuscabbage** [Copilot-Language/Copilot#1]
When I try to build copilot core I get this error:
https://gist.github.com/octopuscabbage/abf529a426ce8c6de1d2

I think it has to do with Applicative now being a superclass of monad.

**Comment by agoodloe** [comment]
thanks we will take a look at the issue and see if we can resolve it as soon as possible

**Comment by GAJaloyan** [comment]
Hi, 

I compiled it, and it seems to work modulo some changes that I pushed already.

I compiled it several times from scratch on a Debian wheezy with the following : 

cabal 1.22.6.0
ghc 7.10.2
caml 4.02.2
branch master for all submodules

And it works well everytime.

All installation details can be found there : https://github.com/Copilot-Language/copilot-discussion/tree/master/TutorialAndDevGuide/DevGuide

Could you please detail more about your configuration if it still does not work on your computer ?

Georges-Axel.

PS : Applicative is a superclass of monad since ghc 7.10, and it compiled well on 7.10.1 this summer. This bug may probably have another cause.

**Comment by chathhorn** [comment]
Yeah, the version of copilot-core in hackage doesn't build on 7.10. We need to get an updated version into the repo. The version here should work, though.

**Comment by t3476** [comment]
I can install it with github's copilot-core but why hasn't repo on hackage been updated?

**Comment by leepike** [comment]
@agoodloe @chathhorn is master stable to push to hackage?

**Comment by agoodloe** [comment]
We have been using this current master for a while here and I it should be
stable enough.

On Tue, Oct 20, 2015 at 12:45 PM, Lee Pike <notifications@github.com> wrote:

> @agoodloe <https://github.com/agoodloe> @chathhorn
> <https://github.com/chathhorn> is master stable to push to hackage?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Copilot-Language/Copilot/issues/1#issuecomment-149628843>
> .
>



-- 
Alwyn E. Goodloe, Ph.D.
agoodloe@gmail.com

Research Computer Engineer
NASA Langley Research Center

**Comment by chathhorn** [comment]
Geh, the version of smtlib2 that works with GHC 7.10 still isn't in hackage. Hold off for a little bit and let me play with the dependencies.

**Comment by agoodloe** [comment]
Good call I've just so used to building it by hand I had overlooked that
one.

On Tue, Oct 20, 2015 at 1:40 PM, Chris Hathhorn <notifications@github.com>
wrote:

> Geh, the version of smtlib2 that works with GHC 7.10 still isn't in
> hackage. Hold off for a little bit and let me play with the dependencies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Copilot-Language/Copilot/issues/1#issuecomment-149643490>
> .
>



-- 
Alwyn E. Goodloe, Ph.D.
agoodloe@gmail.com

Research Computer Engineer
NASA Langley Research Center

**Comment by GAJaloyan** [comment]
Do not forget to also change the dependecies for cabal (if not already done yet) and SBV 5.0 which has been released on hackage.

**Comment by leepike** [comment]
Ok, it builds and the regression test works on my machine. Are we just waiting for smtlib2 to be updated now? @chathhorn, can you ping the maintainer?

**Comment by chathhorn** [comment]
I think it should be alright now, there's a new version of smtlib2 up on hackage that works with 7.10.

Note that copilot-language depends on copilot-theorem, now, though (sorry), so it'll need to be put on hackage too...

**Comment by leepike** [comment]
What about removing sbv and smtlib2 as submodules from Copilot? If they're up-to-date on Hackage, we shouldn't need them as submodules anymore (I'd like to keep submodules limited to Copilot packages).

**Comment by chathhorn** [comment]
I removed them and stuff seems to still be working.

**Comment by leepike** [comment]
Ok, the packages are all updated on Hackage, and I believe they're compatible with both 7.8.3 and 7.10.2. Sorry for the delay!

**Comment by agoodloe** [comment]
Thanks!!!!!!
