### ISSUE TITLE
Add support for new GHC versions to travis

### ISSUE THREAD

**Issue by fdedden** [Copilot-Language/Copilot#14]

**Comment by ivanperez-keera** [comment]
This issue is waiting for the resolutions to:

https://github.com/Copilot-Language/copilot-theorem/issues/3

https://github.com/fdedden/language-c99-simple/issues/1

Solving those issues will let us support GHC 8.6.

**Comment by ivanperez-keera** [comment]
There is another issue that prevents compilation with GHC >= 8.4.

https://github.com/Copilot-Language/copilot-c99/issues/1

For some reason I don't understand, I thought I had compiled this with GHC 8.4, but I must be wrong.

**Comment by ivanperez-keera** [comment]
Ok, the problem is not with copilot-99 or a dependency on pretty-ncols, but that the submodules point to the wrong place.
