### ISSUE TITLE
Typos and style improvements in README

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/Copilot#22]
There's a few typos in the readme, and the style could be clearer.

**Comment by ivanperez-keera** [comment]
Minor question: would it be better to write in the readme:

_> the [Copilot website](https://copilot-language.github.io)._

Instead of writing:

_> the Copilot website: [https://copilot-language.github.io](https://copilot-language.github.io)_

?

**Comment by ivanperez-keera** [comment]
@fdedden I merged some changes into master by mistake. Please, feel free to undo.

**Comment by fdedden** [comment]
> Minor question: would it be better to write in the readme:
> 
> _> the [Copilot website](https://copilot-language.github.io)._
> 
> Instead of writing:
> 
> _> the Copilot website: https://copilot-language.github.io_
> 
> ?

In general it is better to not show the url. In this case I think we should, so that people will recognise and remember the website.
