### ISSUE TITLE
Move from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by fdedden** [Copilot-Language/copilot#222]
There is a banner on the travis-ci.org pages (https://travis-ci.org/github/Copilot-Language/Copilot) that tells the link needs to be updated to travis-ci.com. Seems like it just a new URL, and we can still use it.

**Comment by ivanperez-keera** [comment]
The migration is now complete. The CI setup can now be found at: https://travis-ci.com/github/Copilot-Language/copilot.

As discussed yesterday we need to adjust the README, and make sure the build is compiling properly.
