### ISSUE TITLE
Copilot-c99 exposes too much

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/copilot#237]
The copilot-c99 backend exposes internal modules, types and operations. In principle, only the `Copilot.Compile.C99` module needs to be exposed.

Limiting the API to just that module would make it more abstract and facilitate improving or changing the internals without affecting user code.

This change affects the public API, so it requires deprecation before the modules can be permanently hidden.

**Comment by joeyh** [comment]
I am seeing the deprecation warning when using Copilot.Compile.C99.compile:

  /home/joey/src/arduino-copilot/src/Copilot/Arduino/Main.hs:88:32: warning: [-Wdeprecations]
    In the use of ‘compile’
    (imported from Copilot.Compile.C99, but defined in Copilot.Compile.C99.Compile):
    Deprecated: "This module will be hidden in future versions."
   |
   |                 reify spec >>= compile (mytmpdir </> "copilot")
   |                                ^^^^^^^

I do not think this was the intended result, but it seems ghc imported the deprecation from the deprecated module into the non-deprecated module. 

This was with ghc 8.10.3
