### ISSUE TITLE
`copilot-language`: `DynStableName` without `unsafeCoerce`

### ISSUE THREAD

**Issue by RyanGlScott** [Copilot-Language/copilot#262]
As noted in [_Experience Report: a Do-It-Yourself High-Assurance Compiler_](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.308.6496&rep=rep1&type=pdf), there is a single use of `unsafeCoerce` in `copilot`:

https://github.com/Copilot-Language/copilot/blob/e3f4e84b496a76f05cb615380f77b672438e127b/copilot-language/src/System/Mem/StableName/Dynamic.hs#L16-L28

However, this use of `unsafeCoerce` can be avoided by changing the definition of `DynStableName` slightly. The [`data-reify`](https://hackage.haskell.org/package/data-reify) package uses the same observable-sharing trick that `copilot` does, and `data-reify` defines `DynStableName` [like so](https://github.com/ku-fpg/data-reify/blob/32a28f3c48000cc5fcd2bb5d6f3e2b6c518c5884/Data/Reify.hs#L134-L150):

```hs
data DynStableName = forall a. DynStableName !(StableName a)

instance Hashable DynStableName where
  hashWithSalt s (DynStableName n) = hashWithSalt s n

instance Eq DynStableName where
  DynStableName m == DynStableName n = eqStableName m n

makeDynStableName :: a -> IO DynStableName
makeDynStableName a = do
    st <- makeStableName a
    return $ DynStableName st
```

Note that the use of `unsafeCoerce` in `makeDynStableName` is gone. This is made possible by the fact that:

1. `DynStableName` uses an existential type variable to hide the type of its `StableName`, and
2. The `Eq DynStableName` instance uses [`eqStableName`](https://hackage.haskell.org/package/base-4.15.0.0/docs/System-Mem-StableName.html#v:eqStableName), which does not require that the types of the `StableName`s match.

Note that `eqStableName` is only available in `base-4.7` (GHC 7.8) or later, but I don't think that is an issue for `copilot`.

**Comment by ivanperez-keera** [comment]
The new Copilot requirements allow us to address this change. I'll be adding a normative change request and processing it, ideally as part of the next release.

**Comment by ivanperez-keera** [comment]
**Description**

The library `copilot-language` uses `unsafeCoerce`. This use of `unsafeCoerce` can be avoided by changing the definition of `System.Mem.StableName.Dynamic.DynStableName` and introducing an existential type (akin to how the library `data-reify` defines `DynStableName`).

In our effort to move Copilot to Class D, we have dictated that uses of unsafe code (including functions specifically marked as unsafe in Haskell) should be avoided unless strictly necessary. Consequently, this use should be removed if possible.

**Type**

- Management: conformance with new requirement.

**Additional context**

- None.

**Requester**

- Ryan Scott (Galois).

**Method to check presence of bug**

The following line shows uses of `unsafeCoerce`:

```sh
$ grep -nHre 'unsafeCoerce' --include='*.hs' 
copilot-language/src/System/Mem/StableName/Dynamic.hs:12:import Unsafe.Coerce (unsafeCoerce) -- XXX Not safe!
copilot-language/src/System/Mem/StableName/Dynamic.hs:20:    return (DynStableName (unsafeCoerce stn))
```

**Expected result**

The output of the line above should be empty. The function `unsafeCoerce` should not be used anywhere in the code.
 
**Desired result**

The output of the line above should be empty.

**Proposed solution**

Re-implement `DynStableName` to use an existential type to avoid needing `unsafeCoerce`.

If possible, mark code as `Safe`, as opposed to `TrustWorthy`.

**Further notes**

- See https://github.com/ku-fpg/data-reify/blob/32a28f3c48000cc5fcd2bb5d6f3e2b6c518c5884/Data/Reify.hs#L134-L150 for a definition without `unsafeCoerce`.

- The instance of `Eq` can use [`eqStableName`](https://hackage.haskell.org/package/base-4.15.0.0/docs/System-Mem-StableName.html#v:eqStableName), which does not require that the types of the `StableName`s match.

**Comment by ivanperez-keera** [comment]
Change Manager: Confirmed that the issue exists.

**Comment by ivanperez-keera** [comment]
Technical Lead: Confirmed that the issue should be addressed.

**Comment by ivanperez-keera** [comment]
Technical Lead: Issue scheduled for fixing in Copilot 3.11.

Fix assigned to: @ivanperez-keera .

**Comment by RyanGlScott** [comment]
Was this closed by mistake? I think the commit above meant to refer to #362 rather than this issue (#262).

**Comment by ivanperez-keera** [comment]
Yes, it was. The commit was corrected on the spot, but coincidentally, 262 was open :)

**Comment by ivanperez-keera** [comment]
Implementor: Solution implemented, review requested.

**Comment by ivanperez-keera** [comment]
Change Manager: Verified that:
- Solution is implemented:
  - [X] The code proposed compiles and passes all tests. Details:
    Build log: https://app.travis-ci.com/github/Copilot-Language/copilot/builds/254350096

  - [X] The solution proposed produces the expected result. Details:
    The following Dockerfile checks that the module no longer uses `unsafeCoerce` and prints the message `Success`.
      ```Dockerfile
    FROM ubuntu:trusty
    
    RUN apt-get update
    
    RUN apt-get install --yes git
    
    SHELL ["/bin/bash", "-c"]
    CMD git clone $REPO && cd $NAME && git checkout $COMMIT && cd .. \
        && ! grep -e 'unsafeCoerce' $NAME/copilot-language/src/System/Mem/StableName/Dynamic.hs \
        && echo "Success"
    ```
    Command (substitute variables based on new path after merge):
    ```
    $ docker run -e "REPO=https://github.com/ivanperez-keera/copilot" -e "NAME=copilot" -e "COMMIT=3505027438038806af8523d20a5aef59b520d823" -it copilot-verify-262
    ```
- [X] Implementation is documented. Details:
  No changes to the documentation needed.
- [X] Change history is clear.
- [X] Commit messages are clear.
- [X] Changelogs are updated.
- [X] Examples are updated. Details:
  No updates needed.
- [X] Required version bumps are evaluated. Details:
  No bump needed (no change to the interface).

**Comment by ivanperez-keera** [comment]
Change Manager: Implementation ready to be merged.
