### ISSUE TITLE
Code in README is hard to read

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/Copilot#31]
The code in the README could be presented better (at least with color to aid readability).

There's also a typo. @fdedden recently fixed some typos in `Examples`, so perhaps these changes need to be applied to the readme too.

**Comment by fdedden** [comment]
We could add color, don't know how to do that though without using HTML by hand.

Where's the typo? I have copied the code from the Examples directory.

**Comment by ivanperez-keera** [comment]
I got it.
