### ISSUE TITLE
Why is there no `Typed` instance for Char or String?

### ISSUE THREAD

**Issue by IQubic** [Copilot-Language/copilot#336]
I'm looking through the docs for Copilot and noticing that there's no instance for `Typed Char` or for `Typed String`. From my understanding, this means it's impossible to create a Trigger that is invoked with a Char or with a String as one of its arguments. This seems like a major shortcoming for this library, seeing as these are two very common types in C. Is there some reason for why these two instances don't exist?

**Comment by ivanperez-keera** [comment]
Wrt. `Char`, we have Word8. Does that cover your needs?

Wrt. `String`, we require all arrays to be of fixed length so we can generate hard realtime code with no loops or recursion. You could have a string of up-to X characters. Support for modifying and creating new arrays has been discussed and may be added (TBD).

**Comment by IQubic** [comment]
Actually, that works just fine for me. However, I think I might be using an outdated version of Copilot, because `Word8` doesn't seem to have a `Typeable` instance for me. `Int8` has one. Am I using an outdated version of the library?
